version: "3.8"

services:
  aplazo-backend-challenge:
    container_name: com.aplazo.bnpl.challenge
    build:
      context: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
