version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bnpl_db
      POSTGRES_USER: bnpl_user
      POSTGRES_PASSWORD: bnpl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: openjdk:17-jdk-slim
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bnpl_db
      SPRING_DATASOURCE_USERNAME: bnpl_user
      SPRING_DATASOURCE_PASSWORD: bnpl_password
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew bootRun

volumes:
  postgres_data: