# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never

# Spring Configurations
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:aplazo-backend-challenge}

  # Data Source Configurations
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  # JPA Configurations
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # H2 Configurations
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /api-docs
    enabled: true
  api-docs:
    enabled: true

# Constants
