spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bnpl
    username: bnpl_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "3F9vN1eMkzFvX8TqZdp5WxP2a7+4WmKkXzyBFL7Z01Q="
  expiration: 36000000

logging:
  level:
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
