CREATE TABLE "user"
(
    id bigint generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
);

INSERT INTO "user" ( password, username)
VALUES  ('12345678', 'gonzalo');
